/** @type {import('tailwindcss').Config} */
const {Colors} = require("./constants/Colors");
module.exports = {
    // NOTE: Update this to include the paths to all of your component files.
    content: ["./app/**/*.{js,jsx,ts,tsx}",
        "./components/**/*.{js,jsx,ts,tsx}"],
    presets: [require("nativewind/preset")],
    theme: {
        extend: {
            colors: {
                light: {
                    primary: Colors.light.primary,
                    onPrimary: Colors.light.onPrimary,
                    primaryContainer: Colors.light.primaryContainer,
                    onPrimaryContainer: Colors.light.onPrimaryContainer,
                    secondary: Colors.light.secondary,
                    onSecondary: Colors.light.onSecondary,
                    secondaryContainer: Colors.light.secondaryContainer,
                    onSecondaryContainer: Colors.light.onSecondaryContainer,
                    tertiary: Colors.light.tertiary,
                    onTertiary: Colors.light.onTertiary,
                    tertiaryContainer: Colors.light.tertiaryContainer,
                    onTertiaryContainer: Colors.light.onTertiaryContainer,
                    error: Colors.light.error,
                    onError: Colors.light.onError,
                    errorContainer: Colors.light.errorContainer,
                    onErrorContainer: Colors.light.onErrorContainer,
                    background: Colors.light.background,
                    onBackground: Colors.light.onBackground,
                    surface: Colors.light.surface,
                    onSurface: Colors.light.onSurface,
                    surfaceVariant: Colors.light.surfaceVariant,
                    onSurfaceVariant: Colors.light.onSurfaceVariant,
                    outline: Colors.light.outline,
                    outlineVariant: Colors.light.outlineVariant,
                    shadow: Colors.light.shadow,
                    scrim: Colors.light.scrim,
                    inverseSurface: Colors.light.inverseSurface,
                    inverseOnSurface: Colors.light.inverseOnSurface,
                    inversePrimary: Colors.light.inversePrimary,
                    line: Colors.light.line,
                    elevation: {
                        level0: Colors.light.elevation.level0,
                        level1: Colors.light.elevation.level1,
                        level2: Colors.light.elevation.level2,
                        level3: Colors.light.elevation.level3,
                        level4: Colors.light.elevation.level4,
                        level5: Colors.light.elevation.level5,
                    },
                    surfaceDisabled: Colors.light.surfaceDisabled,
                    onSurfaceDisabled: Colors.light.onSurfaceDisabled,
                    backdrop: Colors.light.backdrop,
                    text: {
                        primary: Colors.light.text.primary,
                        error: Colors.light.text.error,
                        success: Colors.light.text.success,
                    }
                },
                dark: {
                    primary: Colors.dark.primary,
                    onPrimary: Colors.dark.onPrimary,
                    primaryContainer: Colors.dark.primaryContainer,
                    onPrimaryContainer: Colors.dark.onPrimaryContainer,
                    secondary: Colors.dark.secondary,
                    onSecondary: Colors.dark.onSecondary,
                    secondaryContainer: Colors.dark.secondaryContainer,
                    onSecondaryContainer: Colors.dark.onSecondaryContainer,
                    tertiary: Colors.dark.tertiary,
                    onTertiary: Colors.dark.onTertiary,
                    tertiaryContainer: Colors.dark.tertiaryContainer,
                    onTertiaryContainer: Colors.dark.onTertiaryContainer,
                    error: Colors.dark.error,
                    onError: Colors.dark.onError,
                    errorContainer: Colors.dark.errorContainer,
                    onErrorContainer: Colors.dark.onErrorContainer,
                    background: Colors.dark.background,
                    onBackground: Colors.dark.onBackground,
                    surface: Colors.dark.surface,
                    onSurface: Colors.dark.onSurface,
                    surfaceVariant: Colors.dark.surfaceVariant,
                    onSurfaceVariant: Colors.dark.onSurfaceVariant,
                    outline: Colors.dark.outline,
                    outlineVariant: Colors.dark.outlineVariant,
                    shadow: Colors.dark.shadow,
                    scrim: Colors.dark.scrim,
                    inverseSurface: Colors.dark.inverseSurface,
                    inverseOnSurface: Colors.dark.inverseOnSurface,
                    inversePrimary: Colors.dark.inversePrimary,
                    line: Colors.dark.line,
                    elevation: {
                        level0: Colors.dark.elevation.level0,
                        level1: Colors.dark.elevation.level1,
                        level2: Colors.dark.elevation.level2,
                        level3: Colors.dark.elevation.level3,
                        level4: Colors.dark.elevation.level4,
                        level5: Colors.dark.elevation.level5,
                    },
                    surfaceDisabled: Colors.dark.surfaceDisabled,
                    onSurfaceDisabled: Colors.dark.onSurfaceDisabled,
                    backdrop: Colors.dark.backdrop,
                    text: {
                        primary: Colors.dark.text.primary,
                        error: Colors.dark.text.error,
                        success: Colors.dark.text.success,
                    }
                }
            },

        },
        fontFamily: {
            'poppins-black': ['Poppins-Black', 'sans-serif'],
            'poppins-bold': ['Poppins-Bold', 'sans-serif'],
            'poppins-extra-bold': ['Poppins-Extra-Bold', 'sans-serif'],
            'poppins-light': ['Poppins-Extra-Light', 'sans-serif'],
            'poppins-medium': ['Poppins-Medium', 'sans-serif'],
            'poppins-regular': ['Poppins-Regular', 'sans-serif'],
            'poppins-semi-bold': ['Poppins-Semi-Bold', 'sans-serif'],
            'poppins-thin': ['Poppins-Thin', 'sans-serif'],
        }
    },
    plugins: [
        'nativewind/babel',
    ],
}
